WIP

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -230,6 +230,152 @@ jobs:
       - store_artifacts:
           path: /tmp/test-report.csv
 
+  asterius-test-ghc-testsuite-debug:
+    docker:
+      - image: debian:unstable
+    environment:
+      - ASTERIUS_BUILD_OPTIONS: -j2
+      - ASTERIUS_GHC_TESTSUITE_OPTIONS: --debug
+      - DEBIAN_FRONTEND: noninteractive
+      - LANG: C.UTF-8
+      - MAKEFLAGS: -j2
+      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      - STACK_ROOT: /tmp/.stack
+    working_directory: /tmp/asterius
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt full-upgrade -y
+            apt install -y python3-numpy python3-pandas python3-terminaltables
+            apt install -y \
+              automake \
+              cmake \
+              curl \
+              g++ \
+              git \
+              gnupg \
+              libffi-dev \
+              libgmp-dev \
+              libncurses-dev \
+              libnuma-dev \
+              make \
+              openssh-client \
+              python-minimal \
+              python3-minimal \
+              xz-utils \
+              zlib1g-dev
+            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
+            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
+            apt update
+            apt install -y nodejs
+            nodejs --version
+            mkdir -p /root/.local/bin
+            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /root/.local/bin '*/stack'
+
+      - checkout
+      - run:
+            name: Build asterius
+            command: |
+              git submodule update --init --recursive
+              stack --no-terminal -j2 build asterius --test --no-run-tests
+              stack --no-terminal exec ahc-boot
+
+      - run:
+            name: Run GHC test suite on asterius
+            # Allow a large timeout so we have enough time to write out the
+            # CSV file.
+            no_output_timeout: 30m
+            command: |
+              cd ~/.local
+              $CIRCLE_WORKING_DIRECTORY/utils/v8-node.py
+              cd $CIRCLE_WORKING_DIRECTORY
+
+              # run the GHC testsuite and copy the test artifact to `/tmp`
+              nodejs --version
+
+
+              # run test cases that can fail.
+              stack --no-terminal test asterius:ghc-testsuite --test-arguments="--timeout=30s" || true
+              cp asterius/test-report.csv /tmp
+
+      - store_artifacts:
+          path: /tmp/test-report.csv
+
+  asterius-test-ghc-testsuite-debug-yolo:
+    docker:
+      - image: debian:unstable
+    environment:
+      - ASTERIUS_BUILD_OPTIONS: -j2
+      - ASTERIUS_GHC_TESTSUITE_OPTIONS: --debug --yolo
+      - DEBIAN_FRONTEND: noninteractive
+      - LANG: C.UTF-8
+      - MAKEFLAGS: -j2
+      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+      - STACK_ROOT: /tmp/.stack
+    working_directory: /tmp/asterius
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt full-upgrade -y
+            apt install -y python3-numpy python3-pandas python3-terminaltables
+            apt install -y \
+              automake \
+              cmake \
+              curl \
+              g++ \
+              git \
+              gnupg \
+              libffi-dev \
+              libgmp-dev \
+              libncurses-dev \
+              libnuma-dev \
+              make \
+              openssh-client \
+              python-minimal \
+              python3-minimal \
+              xz-utils \
+              zlib1g-dev
+            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
+            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
+            apt update
+            apt install -y nodejs
+            nodejs --version
+            mkdir -p /root/.local/bin
+            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /root/.local/bin '*/stack'
+
+      - checkout
+      - run:
+            name: Build asterius
+            command: |
+              git submodule update --init --recursive
+              stack --no-terminal -j2 build asterius --test --no-run-tests
+              stack --no-terminal exec ahc-boot
+
+      - run:
+            name: Run GHC test suite on asterius
+            # Allow a large timeout so we have enough time to write out the
+            # CSV file.
+            no_output_timeout: 30m
+            command: |
+              cd ~/.local
+              $CIRCLE_WORKING_DIRECTORY/utils/v8-node.py
+              cd $CIRCLE_WORKING_DIRECTORY
+
+              # run the GHC testsuite and copy the test artifact to `/tmp`
+              nodejs --version
+
+
+              # run test cases that can fail.
+              stack --no-terminal test asterius:ghc-testsuite --test-arguments="--timeout=30s" || true
+              cp asterius/test-report.csv /tmp
+
+      - store_artifacts:
+          path: /tmp/test-report.csv
+
   asterius-build-docker:
     docker:
       - image: docker:edge-git
@@ -322,6 +468,8 @@ workflows:
       - asterius-test
       - asterius-test-ghc-testsuite
       - asterius-test-ghc-testsuite-yolo
+      - asterius-test-ghc-testsuite-debug
+      - asterius-test-ghc-testsuite-debug-yolo
       - asterius-build-docker
       - asterius-build-docs
       - asterius-update-docker-tag:
