Improve CircleCI workflow (#231)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,17 +1,17 @@
 version: 2
 
 jobs:
-  asterius-test:
+  asterius-boot:
     docker:
       - image: debian:unstable
     environment:
       - ASTERIUS_BUILD_OPTIONS: -j2
       - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
       - LANG: C.UTF-8
       - MAKEFLAGS: -j2
       - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-      - STACK_ROOT: /tmp/.stack
-    working_directory: /tmp/asterius
+      - WABT_BINDIR: /root/.local/bin
     steps:
       - run:
           name: Install dependencies
@@ -44,12 +44,69 @@ jobs:
       - checkout
 
       - run:
-          name: Build asterius
+          name: Boot
           command: |
             git submodule update --init --recursive
             stack --no-terminal -j2 build --test --no-run-tests
             stack --no-terminal exec ahc-boot
 
+      - persist_to_workspace:
+          root: /root
+          paths:
+            - .local
+            - .stack
+            - project/.stack-work
+            - project/asterius/.stack-work
+            - project/binaryen/.stack-work
+            - project/ghc-toolkit/.stack-work
+            - project/inline-js/inline-js-core/.stack-work
+            - project/npm-utils/.stack-work
+            - project/wabt/.stack-work
+            - project/wasm-toolkit/.stack-work
+            - project/stack.yaml.lock
+
+  asterius-test:
+    docker:
+      - image: debian:unstable
+    environment:
+      - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
+      - LANG: C.UTF-8
+      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt full-upgrade -y
+            apt install -y \
+              automake \
+              cmake \
+              curl \
+              g++ \
+              git \
+              gnupg \
+              libffi-dev \
+              libgmp-dev \
+              libncurses-dev \
+              libnuma-dev \
+              make \
+              openssh-client \
+              python-minimal \
+              python3-minimal \
+              xz-utils \
+              zlib1g-dev
+            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
+            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
+            apt update
+            apt install -y nodejs
+      - checkout
+      - run:
+          name: Initialize submodules
+          command: |
+            git submodule update --init --recursive
+      - attach_workspace:
+          at: /root
       - run:
           name: Test asterius
           command: |
@@ -70,9 +127,9 @@ jobs:
             stack --no-terminal test asterius:fib --test-arguments="--no-gc-sections"
             stack --no-terminal test asterius:fib --test-arguments="--binaryen --no-gc-sections"
 
-            cd ~/.local
-            $CIRCLE_WORKING_DIRECTORY/utils/v8-node.py
-            cd $CIRCLE_WORKING_DIRECTORY
+            cd /root/.local
+            /root/project/utils/v8-node.py
+            cd /root/project
             stack --no-terminal test asterius:fib --test-arguments="--debug" > /dev/null
             stack --no-terminal test asterius:jsffi --test-arguments="--debug" > /dev/null
             stack --no-terminal test asterius:array --test-arguments="--debug" > /dev/null
@@ -91,19 +148,16 @@ jobs:
 
             # Run parts of the ghc-testuite that we have enabled for
             # regression testing.
-            stack test asterius:ghc-testsuite --test-arguments="  --timeout=30s -l test/ghc-testsuite-filter";
+            stack test asterius:ghc-testsuite --test-arguments="--timeout=30s -l test/ghc-testsuite-filter";
 
   asterius-test-ghc-testsuite:
     docker:
       - image: debian:unstable
     environment:
-      - ASTERIUS_BUILD_OPTIONS: -j2
       - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
       - LANG: C.UTF-8
-      - MAKEFLAGS: -j2
       - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-      - STACK_ROOT: /tmp/.stack
-    working_directory: /tmp/asterius
     steps:
       - run:
           name: Install dependencies
@@ -132,17 +186,15 @@ jobs:
             echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
             apt update
             apt install -y nodejs
-            nodejs --version
-            mkdir -p /root/.local/bin
-            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /root/.local/bin '*/stack'
+            node --version
 
       - checkout
       - run:
-            name: Build asterius
-            command: |
-              git submodule update --init --recursive
-              stack --no-terminal -j2 build asterius --test --no-run-tests
-              stack --no-terminal exec ahc-boot
+          name: Initialize submodules
+          command: |
+            git submodule update --init --recursive
+      - attach_workspace:
+          at: /root
 
       - run:
             name: Run GHC test suite on asterius
@@ -151,7 +203,7 @@ jobs:
             no_output_timeout: 30m
             command: |
               # run the GHC testsuite and copy the test artifact to `/tmp`
-              nodejs --version
+              node --version
 
 
               # run test cases that can fail.
@@ -165,14 +217,11 @@ jobs:
     docker:
       - image: debian:unstable
     environment:
-      - ASTERIUS_BUILD_OPTIONS: -j2
       - ASTERIUS_GHC_TESTSUITE_OPTIONS: --yolo
       - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
       - LANG: C.UTF-8
-      - MAKEFLAGS: -j2
       - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-      - STACK_ROOT: /tmp/.stack
-    working_directory: /tmp/asterius
     steps:
       - run:
           name: Install dependencies
@@ -201,17 +250,15 @@ jobs:
             echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
             apt update
             apt install -y nodejs
-            nodejs --version
-            mkdir -p /root/.local/bin
-            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C /root/.local/bin '*/stack'
+            node --version
 
       - checkout
       - run:
-            name: Build asterius
-            command: |
-              git submodule update --init --recursive
-              stack --no-terminal -j2 build asterius --test --no-run-tests
-              stack --no-terminal exec ahc-boot
+          name: Initialize submodules
+          command: |
+            git submodule update --init --recursive
+      - attach_workspace:
+          at: /root
 
       - run:
             name: Run GHC test suite on asterius
@@ -220,7 +267,143 @@ jobs:
             no_output_timeout: 30m
             command: |
               # run the GHC testsuite and copy the test artifact to `/tmp`
-              nodejs --version
+              node --version
+
+
+              # run test cases that can fail.
+              stack --no-terminal test asterius:ghc-testsuite --test-arguments="--timeout=30s" || true
+              cp asterius/test-report.csv /tmp
+
+      - store_artifacts:
+          path: /tmp/test-report.csv
+
+  asterius-test-ghc-testsuite-debug:
+    docker:
+      - image: debian:unstable
+    environment:
+      - ASTERIUS_GHC_TESTSUITE_OPTIONS: --debug
+      - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
+      - LANG: C.UTF-8
+      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt full-upgrade -y
+            apt install -y python3-numpy python3-pandas python3-terminaltables
+            apt install -y \
+              automake \
+              cmake \
+              curl \
+              g++ \
+              git \
+              gnupg \
+              libffi-dev \
+              libgmp-dev \
+              libncurses-dev \
+              libnuma-dev \
+              make \
+              openssh-client \
+              python-minimal \
+              python3-minimal \
+              xz-utils \
+              zlib1g-dev
+            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
+            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
+            apt update
+            apt install -y nodejs
+            node --version
+
+      - checkout
+      - run:
+          name: Initialize submodules
+          command: |
+            git submodule update --init --recursive
+      - attach_workspace:
+          at: /root
+
+      - run:
+            name: Run GHC test suite on asterius
+            # Allow a large timeout so we have enough time to write out the
+            # CSV file.
+            no_output_timeout: 30m
+            command: |
+              cd /root/.local
+              /root/project/utils/v8-node.py
+              cd /root/project
+
+              # run the GHC testsuite and copy the test artifact to `/tmp`
+              node --version
+
+
+              # run test cases that can fail.
+              stack --no-terminal test asterius:ghc-testsuite --test-arguments="--timeout=30s" || true
+              cp asterius/test-report.csv /tmp
+
+      - store_artifacts:
+          path: /tmp/test-report.csv
+
+  asterius-test-ghc-testsuite-debug-yolo:
+    docker:
+      - image: debian:unstable
+    environment:
+      - ASTERIUS_GHC_TESTSUITE_OPTIONS: --debug --yolo
+      - DEBIAN_FRONTEND: noninteractive
+      - GHCRTS: -N2
+      - LANG: C.UTF-8
+      - PATH: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt update
+            apt full-upgrade -y
+            apt install -y python3-numpy python3-pandas python3-terminaltables
+            apt install -y \
+              automake \
+              cmake \
+              curl \
+              g++ \
+              git \
+              gnupg \
+              libffi-dev \
+              libgmp-dev \
+              libncurses-dev \
+              libnuma-dev \
+              make \
+              openssh-client \
+              python-minimal \
+              python3-minimal \
+              xz-utils \
+              zlib1g-dev
+            curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
+            echo "deb https://deb.nodesource.com/node_12.x sid main" > /etc/apt/sources.list.d/nodesource.list
+            apt update
+            apt install -y nodejs
+            node --version
+
+      - checkout
+      - run:
+          name: Initialize submodules
+          command: |
+            git submodule update --init --recursive
+      - attach_workspace:
+          at: /root
+
+      - run:
+            name: Run GHC test suite on asterius
+            # Allow a large timeout so we have enough time to write out the
+            # CSV file.
+            no_output_timeout: 30m
+            command: |
+              cd /root/.local
+              /root/project/utils/v8-node.py
+              cd /root/project
+
+              # run the GHC testsuite and copy the test artifact to `/tmp`
+              node --version
 
 
               # run test cases that can fail.
@@ -259,6 +442,13 @@ jobs:
       DEBIAN_FRONTEND: noninteractive
       LANG: C.UTF-8
     steps:
+      - run:
+          name: Ensure we are on `tweag/asterius`
+          command: |
+            if [ -n "$CIRCLE_PR_NUMBER" ]; then
+              echo "Nothing to do for forked PRs, so marking this step successful"
+              circleci step halt
+            fi
       - run:
           name: Install dependencies
           command: |
@@ -319,9 +509,22 @@ workflows:
   version: 2
   build:
     jobs:
-      - asterius-test
-      - asterius-test-ghc-testsuite
-      - asterius-test-ghc-testsuite-yolo
+      - asterius-boot
+      - asterius-test:
+          requires:
+            - asterius-boot
+      - asterius-test-ghc-testsuite:
+          requires:
+            - asterius-boot
+      - asterius-test-ghc-testsuite-yolo:
+          requires:
+            - asterius-boot
+      - asterius-test-ghc-testsuite-debug:
+          requires:
+            - asterius-boot
+      - asterius-test-ghc-testsuite-debug-yolo:
+          requires:
+            - asterius-boot
       - asterius-build-docker
       - asterius-build-docs
       - asterius-update-docker-tag:
